version: 2
jobs:
  build:
    docker:
      - image: osresearch/heads-builder:18.04
    steps:
      - run:
          name: Install dependencies
          command: |
            apt update
            apt install -y \
              build-essential \
              zlib1g-dev \
              uuid-dev \
              libdigest-sha-perl \
              libelf-dev \
              bc \
              bzip2 \
              bison \
              flex \
              git \
              gnupg \
              iasl \
              m4 \
              nasm \
              patch \
              python \
              wget \
              gnat \
              cpio \
              ccache \
              lzma \

      - checkout

      - run:
          name: Bootstrap make
          command: |
            make bootstrap
      - run:
          name: qemu-coreboot
          command: |
            ./build/make-4.2.1/make \
                -j4 \
                V=1 \
                TOOLCHAIN=/home/builder/heads \
                packages=`pwd`/packages \
                BOARD=qemu-coreboot \

      - run:
          name: qemu-linuxboot
          command: |
            ./build/make-4.2.1/make \
                -j4 \
                V=1 \
                TOOLCHAIN=/home/builder/heads \
                packages=`pwd`/packages \
                BOARD=qemu-linuxboot \

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

