version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - run:
          name: Install dependencies
          command: |
            apt update
            apt install -y \
              build-essential \
              zlib1g-dev \
              uuid-dev \
              libdigest-sha-perl \
              libelf-dev \
              bc \
              bzip2 \
              bison \
              flex \
              git \
              gnupg \
              iasl \
              m4 \
              nasm \
              patch \
              python \
              wget \
              gnat \
              cpio \
              ccache \
              lzma \

      - checkout

      - run:
          name: Bootstrap make
          command: |
            make bootstrap

      - run:
          name: Bootstrap musl
          command: |
            ./build/make-4.2.1/make \
		-j4 \
                V=1 \
                BOARD=qemu-coreboot \
                musl-cross

      - run:
          name: coreboot gcc
          command: |
            ./build/make-4.2.1/make \
                V=1 \
                BOARD=qemu-coreboot \
                coreboot-gcc \

      - run:
          name: qemu-coreboot
          command: |
            ./build/make-4.2.1/make \
                TERM=dumb \
                -j4 \
                V=1 \
                BOARD=qemu-coreboot \
      - store-artifacts:
          path: build/qemu-coreboot/coreboot.rom
      - store-artifacts:
          path: build/qemu-coreboot/hashes.txt

      - run:
          name: qemu-linuxboot
          command: |
            ./build/make-4.2.1/make \
                -j4 \
                V=1 \
                BOARD=qemu-linuxboot \
      - store-artifacts:
          path: build/qemu-linuxboot/linuxboot.rom
      - store-artifacts:
          path: build/qemu-linuxboot/hashes.txt

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

